### ISSUE TITLE
Performance of BAM.quality ?

### ISSUE THREAD

**Issue by jonathanBieler** [BioJulia/XAM.jl#21]
I posted [this](https://github.com/jonathanBieler/ScientificComputingBenchmarks.jl/blob/master/src/Benchmarks/Bioinformatics/Genomics/Genomics.jl) some time ago and someone mentioned that the performance of `BAM.quality` wasn't optimal. I also see in some of my code that it takes a significant portion of time.

Is there a reason for that reinterpret and conversion business ?

https://github.com/BioJulia/BioAlignments.jl/blob/master/src/bam/record.jl#L548

I've tried the following and it seems to work fine:

```julia
function quality(record)
    BAM.checkfilled(record)
    seqlen = BAM.seqlength(record)
    offset = BAM.seqname_length(record) + BAM.n_cigar_op(record, false) * 4 + BAM.cld(seqlen, 2)
    
    return record.data[(1+offset):(seqlen+offset)]
end
```

Cut down the time from 232 to 65 ns. Returning a view cuts it by further by 2. Maybe there's some cases where that fails ? I saw the bam specifications says qualities are char and not uint8.

**Comment by CiaranOMara** [comment]
@jonathanBieler's suggestion was included in https://github.com/BioJulia/XAM.jl/commit/cf168acaa372308451e729708b0670a9e3f0ff3f.

Closes https://github.com/BioJulia/BioAlignments.jl/pull/33
