### ISSUE TITLE
Browsing the documentation 

### ISSUE THREAD

**Issue by george-githinji** [BioJulia/XAM.jl#33]
How do you browse the documentation? Is it possible to simply include a link in the Readme  that links with the documentation markdown files?

**Comment by kescobo** [comment]
Hi George, there are links in the README on "badges"

![image](https://user-images.githubusercontent.com/3502975/110814949-f2ab2480-8257-11eb-8f66-9beb89d4f1d9.png)

If you're not used to looking at the badges (or don't know they're clickable), I can see why you might miss them. The docs for the most recent release can be found here: https://biojulia.net/XAM.jl/stable/
